CREATE TABLE `OUTILS_1_GRILLE` (
  `Corps` varchar(100) DEFAULT NULL,
  `Grade` varchar(100) DEFAULT NULL,
  `Categorie` varchar(2) DEFAULT NULL,
  `echelon` varchar(10) DEFAULT NULL,
  `indice_brut` int DEFAULT NULL,
  `indice_maj` int DEFAULT NULL,
  `duree` varchar(50) DEFAULT NULL,
  `code` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `OUTILS_1_GRILLE` (`Corps`, `Grade`, `Categorie`, `echelon`, `indice_brut`, `indice_maj`, `duree`, `code`) VALUES
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '1', 395, 444, '18', 'AAH_CN_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '2', 415, 469, '24', 'AAH_CN_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '3', 435, 499, '24', 'AAH_CN_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '4', 455, 525, '24', 'AAH_CN_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '5', 485, 567, '30', 'AAH_CN_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '6', 518, 611, '36', 'AAH_CN_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '7', 550, 653, '36', 'AAH_CN_7'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '8', 580, 693, '36', 'AAH_CN_8'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '9', 610, 732, '36', 'AAH_CN_9'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '10', 645, 778, '48', 'AAH_CN_10'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', 'A', '11', 678, 821, NULL, 'AAH_CN_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '1', 389, 373, '12', 'ACH_CN_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '2', 395, 374, '12', 'ACH_CN_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '3', 397, 375, '12', 'ACH_CN_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '4', 401, 376, '12', 'ACH_CN_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '5', 415, 377, '24', 'ACH_CN_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '6', 431, 386, '24', 'ACH_CN_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '7', 452, 401, '24', 'ACH_CN_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '8', 478, 420, '36', 'ACH_CN_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '9', 500, 436, '36', 'ACH_CN_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '10', 513, 446, '36', 'ACH_CN_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '11', 538, 462, '36', 'ACH_CN_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '12', 563, 482, '48', 'ACH_CN_12'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', 'B', '13', 597, 508, NULL, 'ACH_CN_13'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '1', 401, 376, '12', 'ACH_CS_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '2', 415, 377, '12', 'ACH_CS_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '3', 429, 384, '24', 'ACH_CS_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '4', 444, 395, '24', 'ACH_CS_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '5', 458, 406, '24', 'ACH_CS_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '6', 480, 421, '24', 'ACH_CS_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '7', 506, 441, '36', 'ACH_CS_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '8', 528, 457, '36', 'ACH_CS_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '9', 542, 466, '36', 'ACH_CS_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '10', 567, 485, '36', 'ACH_CS_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '11', 599, 509, '48', 'ACH_CS_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', 'B', '12', 638, 539, NULL, 'ACH_CS_12'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '1', 446, 397, '12', 'ACH_CE_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '2', 461, 409, '24', 'ACH_CE_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '3', 484, 424, '24', 'ACH_CE_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '4', 513, 446, '24', 'ACH_CE_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '5', 547, 470, '24', 'ACH_CE_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '6', 573, 489, '36', 'ACH_CE_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '7', 604, 513, '36', 'ACH_CE_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '8', 638, 539, '36', 'ACH_CE_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '9', 660, 556, '36', 'ACH_CE_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '10', 684, 574, '36', 'ACH_CE_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', 'B', '11', 707, 592, NULL, 'ACH_CE_11'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '1', 389, 373, '12', 'AMA_CN_1'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '2', 395, 374, '12', 'AMA_CN_2'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '3', 397, 375, '12', 'AMA_CN_3'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '4', 401, 376, '12', 'AMA_CN_4'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '5', 415, 377, '24', 'AMA_CN_5'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '6', 431, 386, '24', 'AMA_CN_6'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '7', 452, 401, '24', 'AMA_CN_7'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '8', 478, 420, '36', 'AMA_CN_8'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '9', 500, 436, '36', 'AMA_CN_9'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '10', 513, 446, '36', 'AMA_CN_10'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '11', 538, 462, '36', 'AMA_CN_11'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '12', 563, 482, '48', 'AMA_CN_12'),
('Assistant médico-administratif (AMA)', 'Classe normale', 'B', '13', 597, 508, NULL, 'AMA_CN_13'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '1', 401, 376, '12', 'AMA_CS_1'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '2', 415, 377, '12', 'AMA_CS_2'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '3', 429, 384, '24', 'AMA_CS_3'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '4', 444, 395, '24', 'AMA_CS_4'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '5', 458, 406, '24', 'AMA_CS_5'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '6', 480, 421, '24', 'AMA_CS_6'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '7', 506, 441, '36', 'AMA_CS_7'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '8', 528, 457, '36', 'AMA_CS_8'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '9', 542, 466, '36', 'AMA_CS_9'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '10', 567, 485, '36', 'AMA_CS_10'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '11', 599, 509, '48', 'AMA_CS_11'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', 'B', '12', 638, 539, NULL, 'AMA_CS_12'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '1', 446, 397, '12', 'AMA_CE_1'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '2', 461, 409, '24', 'AMA_CE_2'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '3', 484, 424, '24', 'AMA_CE_3'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '4', 513, 446, '24', 'AMA_CE_4'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '5', 547, 470, '24', 'AMA_CE_5'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '6', 573, 489, '36', 'AMA_CE_6'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '7', 604, 513, '36', 'AMA_CE_7'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '8', 638, 539, '36', 'AMA_CE_8'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '9', 660, 556, '36', 'AMA_CE_9'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '10', 684, 574, '36', 'AMA_CE_10'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', 'B', '11', 707, 592, NULL, 'AMA_CE_11'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '1', 542, 466, '6', 'DH_CN_1'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '2', 600, 510, '12', 'DH_CN_2'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '3', 665, 560, '12', 'DH_CN_3'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '4', 713, 596, '12', 'DH_CN_4'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '5', 762, 633, '18', 'DH_CN_5'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '6', 813, 672, '24', 'DH_CN_6'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '7', 862, 710, '24', 'DH_CN_7'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '8', 912, 748, '24', 'DH_CN_8'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '9', 977, 797, NULL, 'DH_CN_9'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', '10', 1015, 826, NULL, 'DH_CN_10'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '1', 797, 660, '24', 'AAH_HC_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '2', 850, 700, '24', 'AAH_HC_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '3', 896, 735, '24', 'AAH_HC_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '4', 946, 773, '30', 'AAH_HC_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '5', 995, 811, '36', 'AAH_HC_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', '6', 1027, 835, NULL, 'AAH_HC_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', 'HEA', NULL, 895, '12', 'AAH_HC_HEA'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', 'HEA2', NULL, 930, '12', 'AAH_HC_HEA2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'A', 'HEA3', NULL, 977, NULL, 'AAH_HC_HEA3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '1', 593, 505, '24', 'AAH_PR_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '2', 639, 540, '24', 'AAH_PR_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '3', 693, 580, '24', 'AAH_PR_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '4', 732, 610, '24', 'AAH_PR_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '5', 791, 655, '24', 'AAH_PR_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '6', 843, 695, '30', 'AAH_PR_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '7', 896, 735, '30', 'AAH_PR_7'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '8', 946, 773, '36', 'AAH_PR_8'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '9', 995, 811, '36', 'AAH_PR_9'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', 'A', '10', 1015, 826, NULL, 'AAH_PR_10'),
('Directeur d\'hôpital (DH)', 'Classe normale', 'A+', 'Eleve dire', 395, 374, NULL, 'DH_CN_ED'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', '1', 1027, 835, '36', 'DH_CE_1'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEA', NULL, 895, '12', 'DH_CE_HEA'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEA2', NULL, 930, '12', 'DH_CE_HEA2'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEA3', NULL, 977, '12', 'DH_CE_HEA3'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEB', NULL, 977, '12', 'DH_CE_HEB'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEB2', NULL, 1018, '12', 'DH_CE_HEB2'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEB3', NULL, 1072, '12', 'DH_CE_HEB3'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEBbis', NULL, 1072, '12', 'DH_CE_HEBbis'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEBbis2', NULL, 1100, '12', 'DH_CE_HEBbis2'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEBbis3', NULL, 1129, '12', 'DH_CE_HEBbis3'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEC', NULL, 1129, '12', 'DH_CE_HEC'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEC2', NULL, 1153, '12', 'DH_CE_HEC2'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HEC3', NULL, 1178, '12', 'DH_CE_HEC3'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HED', NULL, 1178, '12', 'DH_CE_HED'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HED2', NULL, 1231, '12', 'DH_CE_HED2'),
('Directeur d\'hôpital (DH)', 'Classe exceptionnelle', 'A+', 'HED3', NULL, 1284, NULL, 'DH_CE_HED3'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', '1', 813, 672, '24', 'DH_HC_1'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', '2', 862, 710, '24', 'DH_HC_2'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', '3', 912, 748, '24', 'DH_HC_3'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', '4', 977, 797, '36', 'DH_HC_4'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', '5', 1027, 835, '36', 'DH_HC_5'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEA', NULL, 981, '12', 'DH_HC_HEA'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEA2', NULL, 1019, '12', 'DH_HC_HEA2'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEA3', NULL, 1071, '12', 'DH_HC_HEA3'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEB', NULL, 1071, '12', 'DH_HC_HEB'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEB2', NULL, 1115, '12', 'DH_HC_HEB2'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEB3', NULL, 1175, '12', 'DH_HC_HEB3'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEBbis', NULL, 1175, '12', 'DH_HC_HEBbis'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEBbis2', NULL, 1205, '12', 'DH_HC_HEBbis2'),
('Directeur d\'hôpital (DH)', 'Hors classe', 'A+', 'HEBbis3', NULL, 1237, NULL, 'DH_HC_HEBbis3'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '1', 371, 369, '12', 'DH_CP_1'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '2', 431, 386, '24', 'DH_CP_2'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '3', 469, 415, '24', 'DH_CP_3'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '4', 515, 448, '24', 'DH_CP_4'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '5', 574, 490, '24', 'DH_CP_5'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '6', 630, 533, '24', 'DH_CP_6'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '7', 666, 561, '24', 'DH_CP_7'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '8', 690, 578, '36', 'DH_CP_8'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', '9', 715, 598, '36', 'DH_CP_9'),
('Directeur d\'hôpital (DH)', 'Classe provisoire (en voie d\'extinction)', 'A+', 'Echelon fo', 762, 633, NULL, 'DH_CP_EF'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '1', 762, 633, '24', 'DESSMS_HC_1'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '2', 813, 672, '24', 'DESSMS_HC_2'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '3', 862, 710, '24', 'DESSMS_HC_3'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '4', 912, 748, '36', 'DESSMS_HC_4'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '5', 977, 797, '36', 'DESSMS_HC_5'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', '6', 1027, 835, '36', 'DESSMS_HC_6'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEA', NULL, 895, '12', 'DESSMS_HC_HEA'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEA2', NULL, 930, '12', 'DESSMS_HC_HEA2'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEA3', NULL, 977, '12', 'DESSMS_HC_HEA3'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEB', NULL, 977, '12', 'DESSMS_HC_HEB'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEB2', NULL, 1018, '12', 'DESSMS_HC_HEB2'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Hors classe', 'A+', 'HEB3', NULL, 1072, '12', 'DESSMS_HC_HEB3'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', 'Eleve dire', 419, 377, NULL, 'DESSMS_CN_ED'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '1', 511, 445, '12', 'DESSMS_CN_1'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '2', 542, 466, '12', 'DESSMS_CN_2'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '3', 600, 510, '12', 'DESSMS_CN_3'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '4', 665, 560, '24', 'DESSMS_CN_4'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '5', 713, 596, '24', 'DESSMS_CN_5'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '6', 762, 633, '36', 'DESSMS_CN_6'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '7', 813, 672, '36', 'DESSMS_CN_7'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '8', 862, 710, '36', 'DESSMS_CN_8'),
('Directeur d\'établissement sanitaire, social et médico-social (DESSMS)', 'Classe normale', 'A+', '9', 912, 748, NULL, 'DESSMS_CN_9'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '1', 388, 373, '12', 'AA_P1_1'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '2', 397, 375, '12', 'AA_P1_2'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '3', 412, 376, '24', 'AA_P1_3'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '4', 430, 385, '24', 'AA_P1_4'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '5', 448, 398, '24', 'AA_P1_5'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '6', 460, 408, '24', 'AA_P1_6'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '7', 478, 420, '36', 'AA_P1_7'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '8', 499, 435, '36', 'AA_P1_8'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '9', 525, 455, '36', 'AA_P1_9'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de première classe', 'C', '10', 558, 478, NULL, 'AA_P1_10'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '1', 368, 367, '12', 'AA_P2_1'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '2', 371, 369, '12', 'AA_P2_2'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '3', 376, 370, '12', 'AA_P2_3'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '4', 387, 373, '12', 'AA_P2_4'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '5', 396, 374, '12', 'AA_P2_5'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '6', 404, 376, '12', 'AA_P2_6'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '7', 416, 377, '24', 'AA_P2_7'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '8', 430, 385, '24', 'AA_P2_8'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '9', 446, 397, '36', 'AA_P2_9'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '10', 461, 409, '36', 'AA_P2_10'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '11', 473, 417, '48', 'AA_P2_11'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif principal de 2ème classe', 'C', '12', 486, 425, NULL, 'AA_P2_12'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '1', 367, 366, '12', 'AA_P0_1'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '2', 368, 367, '12', 'AA_P0_2'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '3', 370, 368, '12', 'AA_P0_3'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '4', 371, 369, '12', 'AA_P0_4'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '5', 374, 370, '12', 'AA_P0_5'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '6', 378, 371, '12', 'AA_P0_6'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '7', 381, 372, '36', 'AA_P0_7'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '8', 387, 373, '36', 'AA_P0_8'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '9', 401, 376, '36', 'AA_P0_9'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '10', 419, 377, '48', 'AA_P0_10'),
('Adjoint administratif hospitalier (AA)', 'Adjoint administratif hospitalier', 'C', '11', 432, 387, NULL, 'AA_P0_11'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '1', 388, 373, '12', 'PO_P1_1'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '2', 397, 375, '12', 'PO_P1_2'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '3', 412, 376, '24', 'PO_P1_3'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '4', 430, 385, '24', 'PO_P1_4'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '5', 448, 398, '24', 'PO_P1_5'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '6', 460, 408, '24', 'PO_P1_6'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '7', 478, 420, '36', 'PO_P1_7'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '8', 499, 435, '36', 'PO_P1_8'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '9', 525, 455, '36', 'PO_P1_9'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 1ère classe', 'C', '10', 558, 478, NULL, 'PO_P1_10'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '1', 368, 367, '12', 'PO_P2_1'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '2', 371, 369, '12', 'PO_P2_2'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '3', 376, 370, '12', 'PO_P2_3'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '4', 387, 373, '12', 'PO_P2_4'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '5', 396, 374, '12', 'PO_P2_5'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '6', 404, 376, '12', 'PO_P2_6'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '7', 416, 377, '24', 'PO_P2_7'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '8', 430, 385, '24', 'PO_P2_8'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '9', 446, 397, '36', 'PO_P2_9'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '10', 461, 409, '36', 'PO_P2_10'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '11', 473, 417, '48', 'PO_P2_11'),
('Personnels ouvrier (PO)', 'Ouvrier principal de 2ème classe', 'C', '12', 486, 425, NULL, 'PO_P2_12'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '1', 367, 366, '12', 'PO_P0_1'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '2', 368, 367, '12', 'PO_P0_2'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '3', 370, 368, '12', 'PO_P0_3'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '4', 371, 369, '12', 'PO_P0_4'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '5', 374, 370, '12', 'PO_P0_5'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '6', 378, 371, '12', 'PO_P0_6'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '7', 381, 372, '36', 'PO_P0_7'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '8', 387, 373, '36', 'PO_P0_8'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '9', 401, 376, '36', 'PO_P0_9'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '10', 419, 377, '48', 'PO_P0_10'),
('Personnels ouvrier (PO)', 'Agent d\'entretien qualifié', 'C', '11', 432, 387, NULL, 'PO_P0_11'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '1', 388, 373, '12', 'MO_P1_1'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '2', 397, 375, '12', 'MO_P1_2'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '3', 412, 376, '24', 'MO_P1_3'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '4', 430, 385, '24', 'MO_P1_4'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '5', 448, 398, '24', 'MO_P1_5'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '6', 460, 408, '24', 'MO_P1_6'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '7', 478, 420, '36', 'MO_P1_7'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '8', 499, 435, '36', 'MO_P1_8'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '9', 525, 455, '36', 'MO_P1_9'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise principal', 'C', '10', 558, 478, NULL, 'MO_P1_10'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '1', 368, 367, '12', 'MO_P0_1'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '2', 371, 369, '12', 'MO_P0_2'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '3', 376, 370, '12', 'MO_P0_3'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '4', 387, 373, '12', 'MO_P0_4'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '5', 396, 374, '12', 'MO_P0_5'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '6', 404, 376, '12', 'MO_P0_6'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '7', 416, 377, '24', 'MO_P0_7'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '8', 430, 385, '24', 'MO_P0_8'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '9', 446, 397, '36', 'MO_P0_9'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '10', 461, 409, '36', 'MO_P0_10'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '11', 473, 417, '48', 'MO_P0_11'),
('Maitrise ouvrière (MO)', 'Agent de maîtrise', 'C', '12', 486, 425, NULL, 'MO_P0_12'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '1', 444, 395, '12', 'IDE_P0_1'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '2', 484, 424, '18', 'IDE_P0_2'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '3', 514, 447, '24', 'IDE_P0_3'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '4', 544, 468, '24', 'IDE_P0_4'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '5', 576, 491, '30', 'IDE_P0_5'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '6', 611, 518, '36', 'IDE_P0_6'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '7', 653, 550, '36', 'IDE_P0_7'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '8', 693, 580, '36', 'IDE_P0_8'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '9', 732, 610, '48', 'IDE_P0_9'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '10', 778, 645, '48', 'IDE_P0_10'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 1 ISGS', 'A', '11', 821, 678, NULL, 'IDE_P0_11'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '1', 489, 427, '18', 'IDE_P1_1'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '2', 518, 450, '24', 'IDE_P1_2'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '3', 558, 478, '24', 'IDE_P1_3'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '4', 595, 506, '24', 'IDE_P1_4'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '5', 631, 534, '24', 'IDE_P1_5'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '6', 669, 563, '30', 'IDE_P1_6'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '7', 709, 593, '36', 'IDE_P1_7'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '8', 750, 624, '36', 'IDE_P1_8'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '9', 792, 656, '48', 'IDE_P1_9'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '10', 836, 690, '48', 'IDE_P1_10'),
('Infirmier en soins généraux (IDE)', 'Infirmier en soins généraux-Grade 2 ISGS', 'A', '11', 886, 727, NULL, 'IDE_P1_11');
