-- Corps et grades de la Fonction Publique Hospitalière (FPH)

INSERT INTO `OUTILS_1_CORPS` (`Corps`, `Grade`, `code`) VALUES
('Aide-soignant', 'Classe normale', 'AS_CN_1'),
('Aide-soignant', 'Classe supérieure', 'AS_CS_2'),
('Aide-soignant', 'Principal', 'AS_PR_3'),
('Auxiliaire de puériculture', 'Classe normale', 'AP_CN_1'),
('Auxiliaire de puériculture', 'Classe supérieure', 'AP_CS_2'),
('Agent des services hospitaliers qualifié', 'Classe normale', 'ASHQ_CN_1'),
('Agent des services hospitaliers qualifié', 'Classe supérieure', 'ASHQ_CS_2'),
('Agent d''entretien qualifié', 'Classe normale', 'AEQ_CN_1'),
('Agent des services mortuaires et de désinfection', '1re catégorie', 'ASMD_C1_1'),
('Agent de maîtrise', 'Classe normale', 'AM_CN_1'),
('Agent de maîtrise', 'Principal', 'AM_PR_2'),
('Adjoint administratif hospitalier', 'Adjoint administratif', 'AAH_CN_1'),
('Adjoint administratif hospitalier', 'Adjoint administratif principal de 2e classe', 'AAH_P2_2'),
('Adjoint administratif hospitalier', 'Adjoint administratif principal de 1re classe', 'AAH_P1_3'),
('Adjoint des cadres hospitaliers', 'Classe normale', 'ACH_CN_1'),
('Adjoint des cadres hospitaliers', 'Classe supérieure', 'ACH_CS_2'),
('Adjoint des cadres hospitaliers', 'Classe exceptionnelle', 'ACH_CE_3'),
('Assistant médico-administratif', 'Classe normale', 'AMA_CN_1'),
('Assistant médico-administratif', 'Classe supérieure', 'AMA_CS_2'),
('Assistant médico-administratif', 'Classe exceptionnelle', 'AMA_CE_3'),
('Assistant médico-administratif (Assistant de régulation médicale)', 'Classe supérieure', 'AMA_ARM_CS_1'),
('Assistant médico-administratif (Assistant de régulation médicale)', 'Classe exceptionnelle', 'AMA_ARM_CE_2'),
('Animateur', 'Principal de 1re classe', 'ANIM_P1_1'),
('Ambulancier', 'Classe normale', 'AMB_CN_1'),
('Ambulancier', 'Principal', 'AMB_PR_2'),
('Assistant de service social', 'Grade 2', 'ASS_G2_2'),
('Assistant socio-éducatif - Éducateur spécialisé', 'Grade 1', 'ASE_ES_G1_1'),
('Assistant socio-éducatif - Éducateur spécialisé', 'Grade 2', 'ASE_ES_G2_2'),
('Conseiller en économie sociale et familiale', 'Grade 1', 'CESF_G1_1'),
('Conseiller en économie sociale et familiale', 'Grade 2', 'CESF_G2_2'),
('Éducateur de jeunes enfants', 'Grade 1', 'EJE_G1_1'),
('Éducateur de jeunes enfants', 'Grade 2', 'EJE_G2_2'),
('Éducateur technique spécialisé', 'Grade 1', 'ETS_G1_1'),
('Attaché d''administration hospitalière', 'Attaché', 'AAH_ATT_CN_1'),
('Chargé de mission', 'Classe 3', 'CM_C3_1'),
('Chargé de mission', 'Classe unique', 'CM_CN_1'),
('Coordinateur de recherche clinique', 'Niveau 3', 'CRC_N3_1'),
('Attaché de recherche clinique', 'Niveau 2', 'ARC_N2_1'),
('Chef de projet recherche clinique', 'Niveau 4', 'CPR_N4_1'),
('Chef de projet recherche clinique', 'Niveau clinique', 'CPR_CLI_2'),
('Psychologue', 'Classe normale', 'PSY_CN_1'),
('Psychologue', 'Hors classe', 'PSY_HC_2'),
('Physicien médical', 'Classe unique', 'PHYS_CN_1'),
('Audioprothésiste', 'Classe unique', 'AUD_CN_1'),
('Diététicien', 'Classe supérieure', 'DIET_CS_1'),
('Diététicien', 'Cadre de santé', 'DIET_CDS_2'),
('Ergothérapeute', 'Cadre de santé', 'ERGO_CDS_1'),
('Orthophoniste', 'Classe supérieure', 'ORTHO_CS_1'),
('Orthoptiste', 'Classe supérieure', 'ORTPT_CS_1'),
('Pédicure-podologue', 'Classe normale', 'PEDPOD_CN_1'),
('Préparateur en pharmacie hospitalière', 'Classe supérieure', 'PPH_CS_1'),
('Préparateur en pharmacie hospitalière', 'Cadre de santé', 'PPH_CDS_2'),
('Technicien de laboratoire médical', 'Classe supérieure', 'TLM_CS_1'),
('Technicien de laboratoire médical', 'Cadre de santé', 'TLM_CDS_2'),
('Technicien supérieur hospitalier', '1re classe', 'TSH_1CL_1'),
('Technicien supérieur hospitalier', '2e classe', 'TSH_2CL_2'),
('Technicien hospitalier', 'Classe normale', 'TH_CN_1'),
('Dessinateur', 'Principal', 'DESS_PR_1'),
('Ouvrier principal', '2e classe', 'OP_2CL_1'),
('Ouvrier principal', '1re classe', 'OP_1CL_2'),
('Ingénieur hospitalier', 'Ingénieur', 'IH_CN_1'),
('Ingénieur hospitalier', 'Principal', 'IH_PR_2'),
('Ingénieur hospitalier', 'En chef', 'IH_CHEF_3'),
('Ingénieur hospitalier', 'En chef exceptionnel', 'IH_CHEF_CE_4'),
('Ingénieur hospitalier', 'Hors classe', 'IH_HC_5'),
('Manipulateur d''électroradiologie médicale', 'Classe supérieure', 'MERM_CS_1'),
('Manipulateur d''électroradiologie médicale', 'Cadre de santé', 'MERM_CDS_2'),
('Manipulateur d''électroradiologie médicale', 'Cadre supérieur de santé', 'MERM_CSS_3'),
('Masseur-kinésithérapeute', 'Classe normale', 'MK_CN_1'),
('Masseur-kinésithérapeute', 'Classe supérieure', 'MK_CS_2'),
('Masseur-kinésithérapeute', 'Cadre de santé', 'MK_CDS_3'),
('Infirmier en soins généraux et spécialisés', 'Grade 1', 'ISGS_G1_1'),
('Infirmier en soins généraux et spécialisés', 'Grade 2', 'ISGS_G2_2'),
('Infirmier en soins généraux et spécialisés', 'Classe normale', 'IDE_CN_3'),
('Infirmier en soins généraux et spécialisés', 'Classe supérieure', 'IDE_CS_4'),
('Infirmier en soins généraux et spécialisés', 'Cadre de santé', 'IDE_CDS_5'),
('Infirmier en soins généraux et spécialisés', 'Cadre supérieur de santé', 'IDE_CSS_6'),
('Infirmier anesthésiste diplômé d''État', '2e grade', 'IADE_G2_1'),
('Infirmier anesthésiste diplômé d''État', 'Classe supérieure', 'IADE_CS_2'),
('Infirmier anesthésiste diplômé d''État', 'Cadre de santé', 'IADE_CDS_3'),
('Infirmier de bloc opératoire diplômé d''État', 'Grade 2', 'IBODE_G2_1'),
('Infirmier de bloc opératoire diplômé d''État', 'Grade 3', 'IBODE_G3_2'),
('Infirmier de bloc opératoire diplômé d''État', 'Classe supérieure', 'IBODE_CS_3'),
('Infirmier de bloc opératoire diplômé d''État', 'Cadre supérieur de santé', 'IBODE_CSS_4'),
('Puéricultrice', 'Grade 2', 'PUER_G2_1'),
('Puéricultrice', 'Grade 3', 'PUER_G3_2'),
('Puéricultrice', 'Classe supérieure', 'PUER_CS_3'),
('Puéricultrice', 'Cadre de santé', 'PUER_CDS_4'),
('Puéricultrice', 'Cadre supérieur de santé', 'PUER_CSS_5'),
('Sage-femme des hôpitaux', '2e grade - Clinique', 'SF_G2_CLI_1'),
('Sage-femme des hôpitaux', '2e grade - Enseignant', 'SF_G2_ENS_2'),
('Psychomotricien', 'Classe supérieure', 'PSM_CS_1'),
('Auxiliaire médical en pratique avancée', 'Classe normale', 'AMPA_CN_1'),
('Auxiliaire médical en pratique avancée', 'Classe supérieure', 'AMPA_CS_2'),
('Cadre de santé paramédical', 'Infirmier', 'CDS_IDE_1'),
('Cadre de santé paramédical', 'IBODE', 'CDS_IBODE_2'),
('Cadre de santé paramédical', 'IADE', 'CDS_IADE_3'),
('Cadre de santé paramédical', 'Masseur-kinésithérapeute', 'CDS_MK_4'),
('Cadre de santé paramédical', 'Manipulateur en électroradiologie', 'CDS_MERM_5'),
('Cadre de santé paramédical', 'Technicien de laboratoire', 'CDS_TLM_6'),
('Directeur des soins', 'Classe normale', 'DS_CN_1'),
('Directeur des soins', 'Hors classe', 'DS_HC_2'),
('Directeur d''hôpital', 'Hors classe', 'DH_HC_1'),
('Cadre supérieur de santé', 'Infirmier', 'CSS_IDE_1'),
('Cadre supérieur de santé', 'Infirmier anesthésiste', 'CSS_IADE_2'),
('Cadre supérieur de santé', 'Infirmier de bloc opératoire', 'CSS_IBODE_3'),
('Cadre supérieur de santé', 'Puéricultrice', 'CSS_PUER_4'),
('Cadre supérieur de santé', 'Manipulateur d''électroradiologie', 'CSS_MERM_5'),
('Cadre de santé', 'Technicien de laboratoire', 'CDS_TLM_7'),
('Cadre de santé', 'Diététicien', 'CDS_DIET_8'),
('Cadre de santé', 'Ergothérapeute', 'CDS_ERGO_9'),
('Cadre de santé', 'Orthoptiste', 'CDS_ORTHOPT_10'),
('Ingénieur hospitalier', 'Classe normale', 'IH_CN_6'),
('Manipulateur d''électroradiologie médicale', 'Classe exceptionnelle', 'MERM_CE_4'),
('Masseur-kinésithérapeute', 'Classe exceptionnelle', 'MK_CE_4'),
('Infirmier anesthésiste diplômé d''État', 'Cadre supérieur de santé', 'IADE_CSS_4'),
('Infirmier de bloc opératoire diplômé d''État', 'Cadre de santé', 'IBODE_CDS_5'),
('Psychologue', 'Classe exceptionnelle', 'PSY_CE_3'),
('Assistant médico-administratif', 'Assistant de régulation médicale - Classe normale', 'AMA_ARM_CN_3'),
('Préparateur en pharmacie hospitalière', 'Classe normale', 'PPH_CN_3'),
('Technicien de laboratoire médical', 'Classe normale', 'TLM_CN_3'),
('Manipulateur d''électroradiologie médicale', 'Classe normale', 'MERM_CN_5'),
('Orthophoniste', 'Classe normale', 'ORTHO_CN_2'),
('Orthoptiste', 'Classe normale', 'ORTPT_CN_2'),
('Diététicien', 'Classe normale', 'DIET_CN_3'),
('Psychomotricien', 'Classe normale', 'PSM_CN_2'),
('Ergothérapeute', 'Classe normale', 'ERGO_CN_2'),
('Pédicure-podologue', 'Classe supérieure', 'PEDPOD_CS_2'),
('Sage-femme des hôpitaux', '1er grade', 'SF_G1_3'),
('Attaché de recherche clinique', 'Niveau 1', 'ARC_N1_2'),
('Coordinateur de recherche clinique', 'Niveau 2', 'CRC_N2_2'),
('Coordinateur de recherche clinique', 'Niveau 4', 'CRC_N4_3'),
('Chef de projet recherche clinique', 'Niveau 3', 'CPR_N3_3'),
('Chargé de mission', 'Classe 2', 'CM_C2_2'),
('Chargé de mission', 'Classe 1', 'CM_C1_3');


INSERT INTO `OUTILS_1_CORPS` (`Corps`, `Grade`, `code`) VALUES
('Animateur', 'Classe normale', 'ANIM_CN_2'),
('Animateur', 'Principal de 2e classe', 'ANIM_P2_3'),
('Assistant de service social', 'Grade 1', 'ASS_G1_1'),
('Éducateur technique spécialisé', 'Grade 2', 'ETS_G2_2'),
('Attaché d''administration hospitalière', 'Principal', 'AAH_ATT_PR_2'),
('Chargé de mission', 'Classe 4', 'CM_C4_4'),
('Attaché de recherche clinique', 'Niveau 3', 'ARC_N3_3'),
('Ergothérapeute', 'Classe supérieure', 'ERGO_CS_3'),
('Ergothérapeute', 'Cadre supérieur de santé', 'ERGO_CSS_4'),
('Pédicure-podologue', 'Cadre de santé', 'PEDPOD_CDS_3'),
('Pédicure-podologue', 'Cadre supérieur de santé', 'PEDPOD_CSS_4'),
('Infirmier anesthésiste diplômé d''État', '1er grade', 'IADE_G1_5'),
('Directeur d''hôpital', 'Classe normale', 'DH_CN_2'),
('Directeur d''hôpital', 'Classe exceptionnelle', 'DH_CE_3'),
('Puéricultrice', 'Classe normale', 'PUER_CN_6'),
('Technicien de laboratoire médical', 'Cadre supérieur de santé', 'TLM_CSS_4'),
('Masseur-kinésithérapeute', 'Cadre supérieur de santé', 'MK_CSS_5'),
('Infirmier en soins généraux et spécialisés', 'Cadre de santé hors classe', 'ISGS_CDSHC_7'),
('Aumônier', 'Classe unique', 'AUM_CN_1'),
('Aumônier', 'Grille NC2', 'AUM_NC2_2'),
('Coordonnateur en maïeutique', 'Classe unique', 'CMAI_CN_1'),
('Coordonnateur en maïeutique', 'Directeur', 'CMAI_DIR_2'),
('Cadre socio-éducatif', 'Classe unique', 'CSE_CN_1'),
('Chef de projet', 'Classe unique', 'CP_CN_1'),
('Coordinateur d''études cliniques', 'Classe unique', 'CEC_CN_1'),
('Stagiaire école', 'Classe unique', 'STAG_CN_1'),
('Directeur général', 'Hors échelle E', 'DG_HEE_1'),
('Directeur général adjoint', 'Groupe II', 'DGA_G2_1'),
('Directeur d''emploi fonctionnel', 'Groupe II', 'DEF_G2_1'),
('Biostatisticien', 'Junior', 'BIOSTAT_JUN_1'),
('Biostatisticien', 'Sénior', 'BIOSTAT_SEN_2'),
('Gestionnaire de données biomédicales', 'Junior', 'GDB_JUN_1'),
('Gestionnaire de données biomédicales', 'Sénior', 'GDB_SEN_2'),
('Médecin du travail', 'Classe unique', 'MEDTRAV_CN_1'),
('Chargé d''affaires de valorisation', 'Junior', 'CAV_JUN_1'),
('Chargé d''affaires de valorisation', 'Sénior', 'CAV_SEN_2'),
('Chargé de valorisation recherche', 'Niveau 3', 'CVR_N3_1'),
('Chargé de mission recherche', 'Niveau 4', 'CMR_N4_1'),
('Chargé de mission (analyste)', 'Classe unique', 'CMA_CN_1'),
('Chargé de mission (ingénieur)', 'Classe unique', 'CMI_CN_1'),
('Technicien d''étude clinique', 'Classe unique', 'TEC_CN_1'),
('Technicien d''étude clinique', 'Junior', 'TEC_JUN_2'),
('Technicien d''étude clinique', 'Sénior', 'TEC_SEN_3'),
('Assistant(e) de recherche', 'Classe unique', 'AR_CN_1'),
('Audiométriste', 'Classe unique', 'AUDIOM_CN_1'),
('Accompagnant éducatif et social (Aide médico-psychologique)', 'Principal', 'AES_AMP_PR_1'),
('Ingénieur de recherche hospitalier', 'Classe unique', 'IRH_CN_1');
