CREATE TABLE `OUTILS_1_GRILLE` (
  `Corps` varchar(100) DEFAULT NULL,
  `Grade` varchar(100) DEFAULT NULL,
  `echelon` varchar(10) DEFAULT NULL,
  `indice_brut` int DEFAULT NULL,
  `indice_maj` int DEFAULT NULL,
  `duree` varchar(50) DEFAULT NULL,
  `code` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `OUTILS_1_GRILLE` (`Corps`, `Grade`, `echelon`, `indice_brut`, `indice_maj`, `duree`, `code`) VALUES
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '1', 395, 444, '18', 'AAH_CN_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '2', 415, 469, '24', 'AAH_CN_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '3', 435, 499, '24', 'AAH_CN_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '4', 455, 525, '24', 'AAH_CN_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '5', 485, 567, '30', 'AAH_CN_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '6', 518, 611, '36', 'AAH_CN_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '7', 550, 653, '36', 'AAH_CN_7'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '8', 580, 693, '36', 'AAH_CN_8'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '9', 610, 732, '36', 'AAH_CN_9'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '10', 645, 778, '48', 'AAH_CN_10'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché (classe normale)', '11', 678, 821, NULL, 'AAH_CN_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '1', 389, 373, '12', 'ACH_CN_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '2', 395, 374, '12', 'ACH_CN_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '3', 397, 375, '12', 'ACH_CN_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '4', 401, 376, '12', 'ACH_CN_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '5', 415, 377, '24', 'ACH_CN_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '6', 431, 386, '24', 'ACH_CN_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '7', 452, 401, '24', 'ACH_CN_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '8', 478, 420, '36', 'ACH_CN_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '9', 500, 436, '36', 'ACH_CN_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '10', 513, 446, '36', 'ACH_CN_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '11', 538, 462, '36', 'ACH_CN_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '12', 563, 482, '48', 'ACH_CN_12'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe normale', '13', 597, 508, NULL, 'ACH_CN_13'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '1', 401, 376, '12', 'ACH_CS_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '2', 415, 377, '12', 'ACH_CS_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '3', 429, 384, '24', 'ACH_CS_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '4', 444, 395, '24', 'ACH_CS_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '5', 458, 406, '24', 'ACH_CS_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '6', 480, 421, '24', 'ACH_CS_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '7', 506, 441, '36', 'ACH_CS_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '8', 528, 457, '36', 'ACH_CS_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '9', 542, 466, '36', 'ACH_CS_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '10', 567, 485, '36', 'ACH_CS_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '11', 599, 509, '48', 'ACH_CS_11'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe supérieure', '12', 638, 539, NULL, 'ACH_CS_12'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '1', 446, 397, '12', 'ACH_CE_1'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '2', 461, 409, '24', 'ACH_CE_2'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '3', 484, 424, '24', 'ACH_CE_3'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '4', 513, 446, '24', 'ACH_CE_4'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '5', 547, 470, '24', 'ACH_CE_5'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '6', 573, 489, '36', 'ACH_CE_6'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '7', 604, 513, '36', 'ACH_CE_7'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '8', 638, 539, '36', 'ACH_CE_8'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '9', 660, 556, '36', 'ACH_CE_9'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '10', 684, 574, '36', 'ACH_CE_10'),
('Adjoint des cadres hospitaliers (ACH)', 'Classe exceptionnelle', '11', 707, 592, NULL, 'ACH_CE_11'),
('Assistant médico-administratif (AMA)', 'Classe normale', '1', 389, 373, '12', 'AMA_CN_1'),
('Assistant médico-administratif (AMA)', 'Classe normale', '2', 395, 374, '12', 'AMA_CN_2'),
('Assistant médico-administratif (AMA)', 'Classe normale', '3', 397, 375, '12', 'AMA_CN_3'),
('Assistant médico-administratif (AMA)', 'Classe normale', '4', 401, 376, '12', 'AMA_CN_4'),
('Assistant médico-administratif (AMA)', 'Classe normale', '5', 415, 377, '24', 'AMA_CN_5'),
('Assistant médico-administratif (AMA)', 'Classe normale', '6', 431, 386, '24', 'AMA_CN_6'),
('Assistant médico-administratif (AMA)', 'Classe normale', '7', 452, 401, '24', 'AMA_CN_7'),
('Assistant médico-administratif (AMA)', 'Classe normale', '8', 478, 420, '36', 'AMA_CN_8'),
('Assistant médico-administratif (AMA)', 'Classe normale', '9', 500, 436, '36', 'AMA_CN_9'),
('Assistant médico-administratif (AMA)', 'Classe normale', '10', 513, 446, '36', 'AMA_CN_10'),
('Assistant médico-administratif (AMA)', 'Classe normale', '11', 538, 462, '36', 'AMA_CN_11'),
('Assistant médico-administratif (AMA)', 'Classe normale', '12', 563, 482, '48', 'AMA_CN_12'),
('Assistant médico-administratif (AMA)', 'Classe normale', '13', 597, 508, NULL, 'AMA_CN_13'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '1', 401, 376, '12', 'AMA_CS_1'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '2', 415, 377, '12', 'AMA_CS_2'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '3', 429, 384, '24', 'AMA_CS_3'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '4', 444, 395, '24', 'AMA_CS_4'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '5', 458, 406, '24', 'AMA_CS_5'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '6', 480, 421, '24', 'AMA_CS_6'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '7', 506, 441, '36', 'AMA_CS_7'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '8', 528, 457, '36', 'AMA_CS_8'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '9', 542, 466, '36', 'AMA_CS_9'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '10', 567, 485, '36', 'AMA_CS_10'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '11', 599, 509, '48', 'AMA_CS_11'),
('Assistant médico-administratif (AMA)', 'Classe supérieure', '12', 638, 539, NULL, 'AMA_CS_12'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '1', 446, 397, '12', 'AMA_CE_1'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '2', 461, 409, '24', 'AMA_CE_2'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '3', 484, 424, '24', 'AMA_CE_3'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '4', 513, 446, '24', 'AMA_CE_4'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '5', 547, 470, '24', 'AMA_CE_5'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '6', 573, 489, '36', 'AMA_CE_6'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '7', 604, 513, '36', 'AMA_CE_7'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '8', 638, 539, '36', 'AMA_CE_8'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '9', 660, 556, '36', 'AMA_CE_9'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '10', 684, 574, '36', 'AMA_CE_10'),
('Assistant médico-administratif (AMA)', 'Classe exceptionnelle', '11', 707, 592, NULL, 'AMA_CE_11'),
('Directeur d\'hôpital (DH)', 'Classe normale', '1', 542, 466, '6', 'DH_CN_1'),
('Directeur d\'hôpital (DH)', 'Classe normale', '2', 600, 510, '12', 'DH_CN_2'),
('Directeur d\'hôpital (DH)', 'Classe normale', '3', 665, 560, '12', 'DH_CN_3'),
('Directeur d\'hôpital (DH)', 'Classe normale', '4', 713, 596, '12', 'DH_CN_4'),
('Directeur d\'hôpital (DH)', 'Classe normale', '5', 762, 633, '18', 'DH_CN_5'),
('Directeur d\'hôpital (DH)', 'Classe normale', '6', 813, 672, '24', 'DH_CN_6'),
('Directeur d\'hôpital (DH)', 'Classe normale', '7', 862, 710, '24', 'DH_CN_7'),
('Directeur d\'hôpital (DH)', 'Classe normale', '8', 912, 748, '24', 'DH_CN_8'),
('Directeur d\'hôpital (DH)', 'Classe normale', '9', 977, 797, '36', 'DH_CN_9'),
('Directeur d\'hôpital (DH)', 'Classe normale', '10', 1015, 826, NULL, 'DH_CN_10'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '1', 797, 660, '24', 'AAH_HC_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '2', 850, 700, '24', 'AAH_HC_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '3', 896, 735, '24', 'AAH_HC_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '4', 946, 773, '30', 'AAH_HC_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '5', 995, 811, '36', 'AAH_HC_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', '6', 1027, 835, NULL, 'AAH_HC_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'HEA', NULL, 895, '12', 'AAH_HC_HEA'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'HEA2', NULL, 930, '12', 'AAH_HC_HEA2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché hors-classe', 'HEA3', NULL, 977, NULL, 'AAH_HC_HEA3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '1', 593, 505, '24', 'AAH_PR_1'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '2', 639, 540, '24', 'AAH_PR_2'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '3', 693, 580, '24', 'AAH_PR_3'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '4', 732, 610, '24', 'AAH_PR_4'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '5', 791, 655, '24', 'AAH_PR_5'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '6', 843, 695, '30', 'AAH_PR_6'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '7', 896, 735, '30', 'AAH_PR_7'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '8', 946, 773, '36', 'AAH_PR_8'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '9', 995, 811, '36', 'AAH_PR_9'),
('Attaché d\'administration hospitalière (AAH)', 'Attaché principal', '10', 1015, 826, NULL, 'AAH_PR_10');


ALTER TABLE `OUTILS_1_GRILLE`
  ADD UNIQUE KEY `idx_outils_1_grille_code` (`code`);
COMMIT;
